name: poga-py37

channels:
  - conda-forge
  - default

dependencies:
  - python=3.7
  - pip
  - black
  - sphinx
  - pybind11
  - pip:
    - myst_parser>=0.18.1
    - piccolo-theme>=0.12.0
    - line-profiler>=3.5.1

